# Generated by Django 3.0.8 on 2020-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_address', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('device_location', models.CharField(max_length=200)),
                ('vendor', models.CharField(default='/', max_length=200)),
                ('device_model', models.CharField(default='/', max_length=200)),
                ('ios_version', models.CharField(default='/', max_length=200)),
            ],
        ),
    ]
