# Generated by Django 3.0.8 on 2020-08-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='device.Device')),
                ('name', models.CharField(default='/', max_length=200)),
                ('time', models.CharField(default='/', max_length=200)),
                ('detected_vuln', models.CharField(default='/', max_length=200)),
                ('fixed_vuln', models.CharField(default='/', max_length=200)),
                ('configuration_after_fix', models.CharField(default='/', max_length=200)),
                ('configuration_before_fix', models.CharField(default='/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device_State',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='device.Device')),
                ('Last_scan', models.CharField(default='/', max_length=200)),
                ('State', models.CharField(default='/', max_length=200)),
                ('last_backup', models.CharField(default='/', max_length=200)),
                ('backup_time', models.CharField(default='/', max_length=200)),
            ],
        ),
    ]
